## Exercício

Você é um analista de dados em uma empresa e conduziu uma pesquisa de satisfação do cliente durante uma semana. Você perguntou as clientes para classificar seu nível de satisfação com o serviço ao cliente em uma escala de 0 a 10. Você coletou respostas de 30 clientes por dia durante 7 dias, resultando em um total de 210 respostas.

No entanto, os dados que você recebeu estão em um array 1D de 210 elementos. Reorganize os dados de forma a ter as respostas por dia e faça uma análise descritiva básica, calculando a média geral de satisfação e a média diária.

In [10]:
import numpy as np

# considere os seguintes dados aleatórios como início
rng = np.random.default_rng(seed=42)
respostas = rng.integers(low=1, high=10, size=210, endpoint=True)
print(respostas)

[ 1  8  7  5  5  9  1  7  3  1  6 10  8  8  8  8  6  2  9  5  6  4  2 10
  8  7  5  9  6  5  5  3  1  6  9  1  9  9  3  7  2  8  8  4  1 10  5  9
  7  8  8  2  4  5  5  1  6  2  8  7 10  8  4 10  5  4 10  4  1  5  8  2
  5  2  7  5  4  3  6  7 10  5  2  9  7  8  1  4  8  9  5  9  9  4  9  3
  3  7  7  2  9  2  9  1  8  8  8  7  5  8  3  8  6  5  6  6  1  2  3  2
  5  7  7  5  9  6  1  8  6  7  6  6  1  6  8  4  7  1  4  5 10  3  3  5
 10  9  1  3  9  1  9  3 10  3  5  7  2  6  6  8 10  7  5  5  5  9  4  2
  4  1  2  1  8  8  7  5  8  2 10  6 10  2  5  7  5  5  2  4  3  4  7  7
  7  4 10  1  4  2  4 10  4 10  5  7  5  3  8 10  3  8]


O seguinte modelo pode ser pensado para os dados recebidos:

    dia 1 cliente 1, dia 1 cliente 2, dia 1 cliente 3, ...
    ... dia 7 cliente 28, dia 7 cliente 29, dia 7 cliente 30
    
Assim, podemos fazer um reshape:

In [11]:
respostas_ajustadas = respostas.reshape((7,30))
respostas_ajustadas

array([[ 1,  8,  7,  5,  5,  9,  1,  7,  3,  1,  6, 10,  8,  8,  8,  8,
         6,  2,  9,  5,  6,  4,  2, 10,  8,  7,  5,  9,  6,  5],
       [ 5,  3,  1,  6,  9,  1,  9,  9,  3,  7,  2,  8,  8,  4,  1, 10,
         5,  9,  7,  8,  8,  2,  4,  5,  5,  1,  6,  2,  8,  7],
       [10,  8,  4, 10,  5,  4, 10,  4,  1,  5,  8,  2,  5,  2,  7,  5,
         4,  3,  6,  7, 10,  5,  2,  9,  7,  8,  1,  4,  8,  9],
       [ 5,  9,  9,  4,  9,  3,  3,  7,  7,  2,  9,  2,  9,  1,  8,  8,
         8,  7,  5,  8,  3,  8,  6,  5,  6,  6,  1,  2,  3,  2],
       [ 5,  7,  7,  5,  9,  6,  1,  8,  6,  7,  6,  6,  1,  6,  8,  4,
         7,  1,  4,  5, 10,  3,  3,  5, 10,  9,  1,  3,  9,  1],
       [ 9,  3, 10,  3,  5,  7,  2,  6,  6,  8, 10,  7,  5,  5,  5,  9,
         4,  2,  4,  1,  2,  1,  8,  8,  7,  5,  8,  2, 10,  6],
       [10,  2,  5,  7,  5,  5,  2,  4,  3,  4,  7,  7,  7,  4, 10,  1,
         4,  2,  4, 10,  4, 10,  5,  7,  5,  3,  8, 10,  3,  8]],
      dtype=int64)

In [12]:
media_geral_satisfação = respostas.mean()
media_geral_satisfação

5.604761904761904

In [13]:
satisfação_por_cliente = respostas_ajustadas.mean(axis=0)
satisfação_por_cliente

array([6.42857143, 5.71428571, 6.14285714, 5.71428571, 6.71428571,
       5.        , 4.        , 6.42857143, 4.14285714, 4.85714286,
       6.85714286, 6.        , 6.14285714, 4.28571429, 6.71428571,
       6.42857143, 5.42857143, 3.71428571, 5.57142857, 6.28571429,
       6.14285714, 4.71428571, 4.28571429, 7.        , 6.85714286,
       5.57142857, 4.28571429, 4.57142857, 6.71428571, 5.42857143])

In [14]:
satisfação_por_dia = respostas_ajustadas.mean(axis=1)
satisfação_por_dia

array([5.96666667, 5.43333333, 5.76666667, 5.5       , 5.43333333,
       5.6       , 5.53333333])

In [15]:
len(satisfação_por_dia)

7