## Exercício

Você é um analista de RH e tem os salários de todos os funcionários da sua empresa em um array NumPy. Seu trabalho é identificar quantos funcionários ganham acima da média. Use o seguinte array para sua análise: `salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])`.

In [14]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])
salarios


array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])

In [3]:
media_salarios = np.mean(salarios)
media_salarios

3455.5555555555557

In [4]:
ganham_acima_media = salarios[np.where(salarios > media_salarios)]
ganham_acima_media

array([3500, 4000, 4500, 3800, 4800])

In [5]:
print(f'Número de funcionários que ganham acima da média: {len(ganham_acima_media)}')

Número de funcionários que ganham acima da média: 5


# Bonus

Outras formas de fazer contagem

In [6]:
print(np.count_nonzero(salarios > media_salarios))

5


In [7]:
print(np.unique(salarios > media_salarios))

[False  True]


In [9]:
print(np.unique(salarios > media_salarios, return_counts=True))

(array([False,  True]), array([4, 5], dtype=int64))


In [11]:
valores_unicos, contagem = np.unique(salarios > media_salarios, return_counts=True)
print(valores_unicos)
print(contagem)

[False  True]
[4 5]


## Bonus 2

Criando 20 valores fictícios de salários com a mesma faixa anterior, tormando cuidado de outras pessoas gerarem os mesmo valores (repetível)

In [12]:
rng = np.random.default_rng(seed=51)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20)
salarios_gerados

array([3076, 4638, 4617, 2859, 2960, 2713, 2886, 2623, 4304, 4201, 4471,
       2606, 3089, 4256, 3079, 4051, 2101, 3180, 2515, 3377], dtype=int64)

In [13]:
rng = np.random.default_rng(seed=51)

salarios_gerados = rng.integers(low=np.min(salarios), high=np.max(salarios), size=20, endpoint=True)
salarios_gerados

array([3077, 4639, 4618, 2860, 2961, 2713, 2887, 2623, 4305, 4202, 4472,
       2606, 3089, 4256, 3080, 4052, 2101, 3181, 2515, 3377], dtype=int64)

In [15]:
print(np.mean(salarios_gerados))

3380.7


In [16]:
print(salarios_gerados.min())
print(salarios_gerados.max())
print(salarios_gerados.mean())

2101
4639
3380.7
