## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [1]:
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])



In [13]:
ProdA = 0
ProdB = 1
ProdC = 2

In [3]:
vendas.ndim

2

In [4]:
vendas.shape

(3, 5)

In [5]:
vendas[ProdA]

array([50, 60, 70, 65, 80])

In [8]:
vendas_por_dia = vendas.sum(axis=0)
vendas_por_dia

array([207, 225, 216, 234, 244])

In [11]:
vendas_por_produto = vendas.sum(axis=1)
vendas_por_produto

array([325, 433, 368])

In [14]:
print(f"Vendas totais para o Prodto A: {vendas_por_produto[ProdA]}")
print(f"Vendas totais para o Prodto B: {vendas_por_produto[ProdB]}")
print(f"Vendas totais para o Prodto C: {vendas_por_produto[ProdC]}")

Vendas totais para o Prodto A: 325
Vendas totais para o Prodto B: 433
Vendas totais para o Prodto C: 368


In [16]:
for i, d in enumerate(vendas_por_dia):
    print(f"Vendas para o dia {i+1}: {d}")

Vendas para o dia 1: 207
Vendas para o dia 2: 225
Vendas para o dia 3: 216
Vendas para o dia 4: 234
Vendas para o dia 5: 244
