# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [15]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(f'Média salarial: R$ {media_salarial:.2f}')

Média salarial: R$ 3714.29


In [2]:
# Identificar funcionários com salários acima da média
funcionarios_acima_media = np.where(salarios > media_salarial)
funcionarios_acima_media

(array([2, 4, 5, 6], dtype=int64),)

In [3]:
print(salarios[funcionarios_acima_media])

[4000 4500 4000 5000]


In [4]:
print(salarios[np.where(salarios > media_salarial)])

[4000 4500 4000 5000]


In [5]:
print(salarios[salarios > media_salarial])

[4000 4500 4000 5000]


In [6]:
#gera um array de booleanos
salarios > media_salarial

array([False, False,  True, False,  True,  True,  True])

In [7]:
print(salarios[salarios >= 5000])

[5000]


In [8]:
#np.where( CONDIÇÃO, VALOR SE ATENDIDO, VALOR SE NÃO ATENDIDO)
np.where(salarios > media_salarial, "acima da média", "abaixo da média")

array(['abaixo da média', 'abaixo da média', 'acima da média',
       'abaixo da média', 'acima da média', 'acima da média',
       'acima da média'], dtype='<U15')

In [16]:
print(f'Média salarial: R$ {media_salarial:.2f}')
display(salarios)

# dar bônus de 10% para os funcionários com salários abaixo da média

salario_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios)
salario_bonus

Média salarial: R$ 3714.29


array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

array([3300., 3850., 4000., 2200., 4500., 4000., 5000.])

In [18]:
# filtrar os salários entre 3000 e 4500 com where
a = np.where((salarios >= 3000) & (salarios <= 4500))
display(a)
salarios[a]

(array([0, 1, 2, 4, 5], dtype=int64),)

array([3000, 3500, 4000, 4500, 4000])

In [19]:
#ajustar os salários entre 3000 e 4500 com where
salario_ajustados = np.where((salarios >= 3000) & (salarios <= 4500), salarios * 1.05, salarios)
salario_ajustados

array([3150., 3675., 4200., 2000., 4725., 4200., 5000.])

In [20]:
# filtrar os salários abaixo de 3000 ou acima de 4500 com where
b = np.where((salario_ajustados < 3000) | (salario_ajustados > 4500))
b


(array([3, 4, 6], dtype=int64),)

In [22]:
#ajusta os salários abaixo de 3000 ou acima de 4500 com where
salarios_segundo_ajuste = np.where((salario_ajustados < 3000) | (salario_ajustados > 4500), salario_ajustados * 1.1, salario_ajustados)
salarios_segundo_ajuste

array([3150. , 3675. , 4200. , 2200. , 5197.5, 4200. , 5500. ])