## Exercício

Você é um engenheiro de produção e tem os tempos de ciclo (em minutos) de uma linha de produção em um array NumPy. Seu trabalho é identificar quaisquer tempos de ciclo que estão dois desvios padrão acima ou abaixo da média. Use o seguinte array para sua análise: `tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])`. 

In [67]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8, 4.1])
media = np.mean(tempos_ciclo) 

Considerando uma distribuição normal:

![normal](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Standard_deviation_diagram_micro.svg/640px-Standard_deviation_diagram_micro.svg.png)

In [68]:
desvio_padrao = tempos_ciclo.std()
desvio_padrao

0.7590125163658372

In [69]:
desvio2 = desvio_padrao * 2

limite_superior = media + desvio2
limite_inferior = media - desvio2

condicao_a = tempos_ciclo > limite_superior
condicao_b = tempos_ciclo < limite_inferior
condicao = condicao_a | condicao_b

anomalias = np.where(condicao)
anomalias

(array([7, 9], dtype=int64),)

In [70]:
outliers = tempos_ciclo[anomalias]
outliers

array([7.2, 4.1])

In [71]:
print('Os tempos anomalos são ', outliers)

Os tempos anomalos são  [7.2 4.1]


# Bonus

In [72]:
condicao = (tempos_ciclo > media + desvio_padrao * 2) | (tempos_ciclo < media - desvio_padrao * 2)
condicao


array([False, False, False, False, False, False, False,  True, False,
        True])

In [73]:

anomalias = np.where(condicao)
anomalias

(array([7, 9], dtype=int64),)

In [74]:
condicao_contraria = (tempos_ciclo <= media + desvio_padrao * 2) & (tempos_ciclo >= media - desvio_padrao * 2)
condicao_contraria

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False])

In [75]:
condicao_contraria = ~condicao
condicao_contraria

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
       False])

In [76]:
np.where(~condicao)

(array([0, 1, 2, 3, 4, 5, 6, 8], dtype=int64),)

## Bonus 2

In [77]:
rng = np.random.default_rng(seed=99)
tempos_gerados = rng.normal(loc=media, scale=desvio_padrao, size=100)
print(tempos_gerados)

[5.69261421 5.27750061 5.66834157 6.15085778 4.29657402 6.90850467
 5.28249155 5.17730968 4.83533852 6.33724181 6.14231864 6.57454645
 6.30786453 5.82962404 5.87934916 6.33986167 4.96388075 5.59516429
 5.91984543 5.28651725 6.17775268 5.36270357 6.14066136 5.73673484
 5.98108935 4.47808244 4.97702339 6.65054453 5.76516975 5.5682784
 6.36146093 6.19993408 5.59450963 5.14189356 7.11837408 6.15426547
 4.43679049 6.2671648  6.21328443 6.2477738  5.32343875 6.74675883
 5.06225908 6.54926713 5.85207679 6.91830147 5.33503876 6.1585945
 6.27123773 5.38426159 5.63854057 5.31531128 5.99299264 6.1526141
 5.40862944 5.89256945 5.18834176 5.23447944 4.17073251 4.73888724
 5.11847587 5.71211207 6.78394949 5.8342059  5.69934412 5.89406127
 4.56625274 5.66672107 4.97109061 5.1945389  7.17557804 7.03217908
 6.37167082 6.04214944 6.01223766 4.8974627  4.67709707 5.88405662
 5.29057473 5.04046    5.56903429 5.57499201 5.77362289 5.06863459
 5.64313692 4.68935004 6.56118106 6.78309461 4.79174735 5.9543316

In [78]:
print(media)
print(tempos_gerados.mean())

5.63
5.711762609749175


In [79]:
condicao = (tempos_gerados > tempos_gerados.mean() + tempos_gerados.std() * 2) | (tempos_gerados < tempos_gerados.mean() - tempos_gerados.std() * 2)
condicao

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [80]:
display(np.where(condicao))
display(tempos_gerados[condicao])

(array([ 4, 34, 58, 70, 71], dtype=int64),)

array([4.29657402, 7.11837408, 4.17073251, 7.17557804, 7.03217908])